# ==========================================================
# ft_transcendence
#
# Architecture :
#
#            Internet
#                │
#              Nginx
#             /     \
#      Frontend    Backend
#                     │
#                PostgreSQL
#
# Chaque service est isolé dans son propre container Docker.
# Toutes les communications internes passent par le réseau Docker
# "transcendence"
# ==========================================================


services:
  postgres:
    container_name: postgres
    image: postgres:local
    build: ./requirements/postgres
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./secrets:/run/secrets:ro
    networks:
      - transcendence
    restart: unless-stopped

  backend:
    container_name: backend
    image: backend:local
    build: ./requirements/backend
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - ./secrets:/run/secrets:ro
      - uploads_data:/app/uploads
    networks:
      - transcendence
    restart: unless-stopped

  game:
    container_name: game
    image: game:local
    build: ./requirements/game
    env_file:
      - .env
    volumes:
      - ./secrets:/run/secrets:ro
    networks:
      - transcendence
    restart: unless-stopped

  frontend:
    container_name: frontend
    image: frontend:local
    build: ./requirements/frontend
    env_file:
      - .env
    depends_on:
      - backend
    networks:
      - transcendence
    restart: unless-stopped


  nginx:
    container_name: nginx
    image: nginx:local
    build: ./requirements/nginx
    env_file:
      - .env

    # nginx est démarré après le backend.
    # Attention : depends_on veut dire "démarré", pas forcément "prêt".
    depends_on:
      - frontend
      - backend
      - game

    # nginx sera le seul point d'entrée vers l'extérieur.
    # Le navigateur parle à la machine hôte sur ${NGINX_PORT}
    # puis Docker redirige vers le port 443 du container nginx.
    ports:
      - "${NGINX_PORT}:443"

    # nginx aura besoin des certificats TLS.
    # :ro = read-only : nginx peut lire les secrets mais pas les modifier.
    volumes:
      - ./secrets:/run/secrets:ro
      - uploads_data:/app/uploads:ro


    networks:
      - transcendence

    restart: unless-stopped





networks:
  transcendence:
    name: transcendence
    driver: bridge



volumes:
  postgres_data:
    driver: local

  uploads_data:
    driver: local
