events {}

http
{
    server
    {
        # Écoute sur le port HTTPS.
        listen 443 ssl;

        # Nom de domaine attendu.
        server_name localhost;

        # On accepte pas de dl une image superieur a 2Mo
        client_max_body_size 2M;

        # Certificat TLS.
        ssl_certificate /etc/nginx/ssl/nginx.crt;
        ssl_certificate_key /etc/nginx/ssl/nginx.key;

        # Versions TLS autorisées.
        ssl_protocols TLSv1.2 TLSv1.3;


        location /uploads/
        {
            alias /app/uploads/;
        }


        location /
        {
            proxy_pass http://frontend:5173;
        }

        location /api/
        {
            proxy_pass http://backend:3000;
        }
    }
}










# events {}

# C’est un bloc nginx obligatoire dans une configuration complète.

# Il sert à la gestion bas niveau des connexions réseau.

# Dans notre cas, il est vide, donc nginx utilise les paramètres par défaut.

# C'est un bloc technique obligatoire mais qui ne nécessite aucune configuration ici.







# http { ... }

# C’est le bloc principal concernant tout le trafic HTTP/HTTPS.

# C’est ici que l’on configure :

# les serveurs (virtual hosts)
# les règles de routage
# le reverse proxy
# les certificats TLS
# les futures communications avec le frontend et le backend







# server { ... }

# C’est un "virtual host".

# En résumé :

# "Si une requête arrive pour ce domaine,
# applique toutes les règles définies dans ce bloc."








# listen 443 ssl;

# nginx écoute sur le port HTTPS (443).

# Toutes les connexions seront chiffrées grâce à TLS.







# server_name mwallis.42.fr;

# Nom de domaine attendu.

# Plus tard il pourra être remplacé par :

# localhost
# transcendence.local
# aimpostor.42.fr

# suivant l'environnement de développement ou de production.








# ssl_certificate /etc/nginx/ssl/nginx.crt;
# ssl_certificate_key /etc/nginx/ssl/nginx.key;

# nginx utilise ces deux fichiers pour établir
# une connexion HTTPS sécurisée.

# nginx.crt = certificat public
# nginx.key = clé privée

# Sans eux, HTTPS ne fonctionne pas.







# ssl_protocols TLSv1.2 TLSv1.3;

# On n'autorise que les protocoles TLS récents.

# TLS 1.2
# TLS 1.3

# Les anciennes versions sont volontairement désactivées
# pour des raisons de sécurité.








# location / { ... }

# Cette règle s'applique à toutes les requêtes arrivant
# sur le site.

# Pour le moment, elle ne fait qu'envoyer une réponse texte.

# Cela permet de vérifier :

# que nginx démarre correctement
# que HTTPS fonctionne
# que le certificat est valide
# que Docker est correctement configuré

# Plus tard, ce bloc deviendra le point d'entrée
# du frontend React.

# Exemple futur :

# location /
# {
#     proxy_pass http://frontend:3000;
# }








# Dans les prochaines étapes du projet, nous ajouterons
# progressivement de nouvelles règles :

# /            -> Frontend React

# /api         -> Backend NestJS

# /socket.io   -> Socket.IO (WebSocket)

# nginx deviendra alors un Reverse Proxy.








# Pour résumer, nginx fera :

# recevoir toutes les connexions HTTPS

# servir le frontend React

# rediriger les requêtes API vers le backend NestJS

# rediriger les connexions WebSocket vers Socket.IO

# renvoyer la réponse au navigateur

# le tout derrière une seule adresse HTTPS.