# PostgreSQL Configuration File

# postgresql.conf est le fichier de configuration principal
# du serveur PostgreSQL.
#
# Il permet de configurer le comportement du serveur :
# - réseau
# - performances
# - mémoire
# - logs
# - authentification
# - réplication
#
# Pour le moment, nous n'avons besoin que d'une seule option.




# Réseau

# listen_addresses
#
# Définit sur quelles interfaces réseau PostgreSQL écoute.
#
# Par défaut :
#
#   listen_addresses = 'localhost'
#
# PostgreSQL accepte uniquement les connexions locales
# à l'intérieur du container.
#
# Comme notre backend (NestJS) sera dans un autre container,
# PostgreSQL doit accepter les connexions provenant du réseau Docker.
#
# '*' signifie :
#
# écouter sur toutes les interfaces réseau disponibles.
#
# Le réseau Docker restant privé, cela ne rend pas PostgreSQL
# accessible directement depuis Internet.
#
# Les connexions extérieures resteront contrôlées par Docker
# et notre docker-compose.yml.

listen_addresses = '*'